# Generated by Django 5.1.5 on 2025-02-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_address_line_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='secondary_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_first_last_name'),
        ),
    ]
