# Generated by Django 5.1.5 on 2025-02-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_contact_secondary_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_label',
            field=models.CharField(choices=[('HOME', 'home'), ('WORK', 'work')], default='HOME', max_length=4),
        ),
    ]
