# Generated by Django 5.1.5 on 2025-02-05 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_address_address_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobile_number',
            new_name='primary_phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+?1?\\d(9, 15)$')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_label',
            field=models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work')], default='HOME', max_length=4),
        ),
    ]
