# Generated by Django 5.1.5 on 2025-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_rename_mobile_number_contact_primary_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
