# Generated by Django 5.1.5 on 2025-03-29 22:57

import contacts.address.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_address_created_at_address_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, validators=[contacts.address.validators.validators.validate_uk_postcode]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='primary_phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[contacts.address.validators.validators.validate_uk_landline, contacts.address.validators.validators.validate_uk_mobile]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[contacts.address.validators.validators.validate_uk_landline, contacts.address.validators.validators.validate_uk_mobile]),
        ),
    ]
